version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: atlasuser
      POSTGRES_PASSWORD: atlaspass
      POSTGRES_DB: atlasdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
